#!/bin/bash
# Wrapper script to build Xilinx design using Windows Vivado from WSL
# Usage: ./build_xilinx_wsl.sh <build_dir> <top_module> <part>

BUILD_DIR=$1
TOP_MODULE=$2
PART=$3

PROJECT_ROOT=$(pwd)

# Create build directory
mkdir -p "$BUILD_DIR"

echo "=========================================="
echo "Building Xilinx Design via WSL"
echo "Project Root: $PROJECT_ROOT"
echo "Build Directory: $BUILD_DIR"
echo "Top Module: $TOP_MODULE"
echo "Part: $PART"
echo "=========================================="

# Create a temporary Windows directory for the build
# Use C:\Temp for better compatibility
BUILD_PID=$$
WIN_BUILD_DIR="C:\\Temp\\fpga_i2c_build_${BUILD_PID}"
WSL_WIN_BUILD_DIR="/mnt/c/Temp/fpga_i2c_build_${BUILD_PID}"

echo "Creating temporary Windows build directory..."
mkdir -p "$WSL_WIN_BUILD_DIR"

# Copy source files to Windows temp directory
echo "Copying source files..."
cp -r rtl "$WSL_WIN_BUILD_DIR/"
cp -r include "$WSL_WIN_BUILD_DIR/"
cp -r constraints "$WSL_WIN_BUILD_DIR/"
mkdir -p "$WSL_WIN_BUILD_DIR/output"

# Create TCL build script in Windows temp directory
cat > "$WSL_WIN_BUILD_DIR/build.tcl" <<EOFTCL
# Vivado TCL Build Script for I2C Slave (WSL version)
# Auto-generated by build_xilinx_wsl.sh

set work_dir "C:/Temp/fpga_i2c_build_${BUILD_PID}"
set output_dir "\$work_dir/output"
set top_module "$TOP_MODULE"
set part "$PART"

puts "=========================================="
puts "Vivado Build Script for I2C Slave"
puts "Work Directory: \$work_dir"
puts "Output Directory: \$output_dir"
puts "Top Module: \$top_module"
puts "Part: \$part"
puts "=========================================="

# Create project in memory (non-project mode for scripting)
set project_name "i2c_slave"
create_project -in_memory -part \$part

# Add source files
cd \$work_dir
read_verilog -sv rtl/i2c_slave_top_diffclk.v
read_verilog -sv rtl/version_storage.v
read_verilog -sv rtl/version_i2c_slave.v
read_xdc constraints/xilinx/xc7s50.xdc

# Set include directories
set_property include_dirs [list "\$work_dir/include"] [current_fileset]

# Set top module
set_property top \$top_module [current_fileset]

# Run synthesis
puts "Running synthesis..."
synth_design -top \$top_module -part \$part -flatten_hierarchy rebuilt

# Write checkpoint
write_checkpoint -force "\$output_dir/\${project_name}_synth.dcp"

# Run implementation
puts "Running optimization..."
opt_design

puts "Running placement..."
place_design

puts "Running routing..."
route_design

# Write checkpoint
write_checkpoint -force "\$output_dir/\${project_name}_route.dcp"

# Generate reports
report_utilization -file "\$output_dir/utilization.rpt"
report_timing_summary -file "\$output_dir/timing_summary.rpt"

# Generate bitstream
puts "Generating bitstream..."
write_bitstream -force "\$output_dir/\${project_name}.bit"

puts "Build complete: \$output_dir/\${project_name}.bit"
puts "=========================================="
EOFTCL

# Run Vivado from Windows temp directory
echo "Launching Vivado..."
cd "$WSL_WIN_BUILD_DIR"
cmd.exe /c "cd $WIN_BUILD_DIR && C:\\Xilinx\\2025.1\\Vivado\\bin\\vivado.bat -mode batch -source build.tcl"

EXIT_CODE=$?

# Copy results back to WSL
if [ $EXIT_CODE -eq 0 ]; then
    echo "=========================================="
    echo "Build completed successfully!"
    echo "Copying results back to project..."
    cp -r "$WSL_WIN_BUILD_DIR/output/"* "$PROJECT_ROOT/$BUILD_DIR/"
    echo "Bitstream: $BUILD_DIR/i2c_slave.bit"
    echo "=========================================="

    # Cleanup
    echo "Cleaning up temporary files..."
    rm -rf "$WSL_WIN_BUILD_DIR"
else
    echo "=========================================="
    echo "Build failed with exit code: $EXIT_CODE"
    echo "Temporary build directory preserved at: $WSL_WIN_BUILD_DIR"
    echo "=========================================="
    exit $EXIT_CODE
fi
